version: "3"

volumes:
  postgres-data-volume:
    driver: local

services:
  nginx:
    container_name: nginx.service
    build:
      context: nginx
    ports:
      - 22000:80
    volumes:
      #монтируем файл в директорию контейнера
      - ./nginx-data/upstreams.conf:/etc/nginx/conf.d/upstreams.conf:ro
    depends_on:
      - frontend
      - backend1
      - backend2
  postgres:
    container_name: postgres.service
    image: "postgres:13.0"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: example
    ports:
      - 22001:5432
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data #именованный том
      - ./postgres/data.sql:/docker-entrypoint-initdb.d/data.sql

  frontend:
    container_name: frontend.service
    build:
      context: frontend
    ports:
      - 22002:3000
    volumes:
      - ./frontend/:/app/

  backend1:
    container_name: backend1.service
    build:
      context: backend
    ports:
      - 22003:7000
    volumes:
      - ./backend1-data/application.properties:/app/application.properties

  backend2:
    container_name: backend2.service
    build:
      context: backend
    ports:
      - 22004:7000
    volumes:
      - ./backend2-data/application.properties:/app/application.properties:ro
    depends_on:
      - postgres